### ISSUE TITLE
Add link to npmarket repo/issue tracker

### ISSUE THREAD

**Issue by 0joshuaolson1** [QingWei-Li/npmarket#10]
So it's easier to get help/see how it works.

**Comment by QingWei-Li** [comment]
![2018_2_13_ 2_43](https://user-images.githubusercontent.com/7565692/36113512-04d5cddc-1068-11e8-954c-3c5f8d54cce3.png)



This link?

**Comment by 0joshuaolson1** [comment]
...maybe
