### ISSUE TITLE
Mac下webstorm打开项目<style>标签内容报错

### ISSUE THREAD

**Issue by Benjamin-UnderWood** [QingWei-Li/npmarket#9]
我在webstorm下安装了 postcss插件 仍然不好使
———————————22：00分割线—————————————————
`<style>
  .PkgHeader {
    &__github {
      color: inherit;

      &:hover {
        text-decoration: none;
        opacity: .6;
      }

      .iconfont {
        font-size: 20px;
      }
    }

    &__header {
      border-bottom: 1px solid rgba(#9CA3A9, .1);
      box-sizing: border-box;
      position: relative;
      height: 72px;
      padding: 0 20px;
      display: flex;
      align-items: center;

      &__info {
        flex: 1;
      }

      &__links {
        width: 300px;
        text-align: right;
        margin-right: 20px;
      }
    }

    &__title {
      font-size: 30px;
      font-weight: bold;
    }

    &__desc {
      margin-top: 4px;
    }
  }`

**Comment by QingWei-Li** [comment]
请列出终端里的报错信息，同时推荐用 yarn 安装依赖，最近 postcss 升级到 6.x 导致 postcss-salad 无法工作

**Comment by Benjamin-UnderWood** [comment]
并不是终端的报错， npm run dev 正常运行。而是webstorm IDE 里的报错。

**Comment by QingWei-Li** [comment]
IDE 的问题请到相应社区提问，我并不用 ws
